apiVersion: v1
kind: Service
metadata:
  name: microservice-load-balancer
  namespace: gasta-ns
  labels:
    app: microservice-load-balancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: company-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
