apiVersion: v1
kind: Service
metadata:
  name: microservice-load-balancer
spec:
  type: LoadBalancer
  selector:
    category: microservice
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
